// const myArr = [0, 1, 2, 3, 4];
// const myHeros = ["Shaktiman", "Naagraj"];
// const myArr2 = new Array (1, 2, 3, 4, 5);
// console.log(myArr["one"]);
// console.log(myArr[0]);
// myArr.push(6);
// console.log(myArr);
// myArr.pop();
// console.log(myArr);
// myArr.unshift(9);
// console.log(myArr);
// myArr.shift();
// console.log(myArr);
// console.log(myArr.includes(9));
// console.log(myArr.indexOf(2));
// const newArr = myArr.join();
// console.log(newArr);
// console.log("A ", myArr);
// const myn1 = myArr.slice(1, 3);
// console.log("B ",myn1);
// const myn2 = myArr.splice(1, 3);
// console.log("C ", myn2);
// console.log("D ",myArr);
// const marvel_heros = ["thor", "Ironman", "Spierman"];
// const dc_heros = ["Superman", "Flash", "Batman"];
// marvel_heros.push(dc_heros);
// console.log(marvel_heros);
// console.log(marvel_heros[3][0]);
// const all_heros = marvel_heros.concat(dc_heros);
// console.log(all_heros);
// console.log(marvel_heros);
// const all_new_heros = [...marvel_heros, ...dc_heros];
// console.log(all_new_heros);
// const another_array = [1, 2, 3, [4, 5, 6], 7, [6, 7, [4, 5]]];
// const real_numbers = another_array.flat(2);
// console.log(real_numbers);
// console.log(Array.isArray("Hitesh"));
// console.log(Array.isArray(marvel_heros));
// console.log(Array.from("Hitesh"));
// console.log(Array.from({name: "Hitesh"}));
// console.log(Array.from({0: "Hitesh", length: 1}));