const myArr = [0, 1, 2, 3, 4];
// const myHeros = ["Shaktiman", "Naagraj"];
// const myArr2 = new Array (1, 2, 3, 4, 5);
// console.log(myArr["one"]);
// console.log(myArr[0]);
// myArr.push(6);
// console.log(myArr);
// myArr.pop();
// console.log(myArr);
// myArr.unshift(9);
// console.log(myArr);
// myArr.shift();
// console.log(myArr);
// console.log(myArr.includes(9));
// console.log(myArr.indexOf(2));
// const newArr = myArr.join();
// console.log(newArr);
// console.log("A ", myArr);
// const myn1 = myArr.slice(1, 3);
// console.log("B ",myn1);
// const myn2 = myArr.splice(1, 3);
// console.log("C ", myn2);
// console.log("D ",myArr);